-- groups

return {
    -- syntax
    Structure    = {link='Normal'}, 
    Number       = {link='Normal'}, 
    Float        = {link='Normal'}, 
    Delimiter    = {link='Normal'}, 
    Operator     = {link='Normal'}, 
    StorageClass = {link='Keyword'},
    Conditional  = {link='Keyword'},
    Boolean      = {link='Keyword'},
    Repeat       = {link='Keyword'},
    Exception    = {link='Keyword'},
    Statement    = {link='Label'},

    -- clang
    cType         = {link='Type'},
    cTypeDef      = {link='Type'},
    cFormat       = {link='Special'},
    cStorageClass = {link='StorageClass'},

    -- rust
    rustSigil                                 = {link='Normal'},
    rustFoldBraces                            = {link='Normal'},
    rustModPath                               = {link='Normal'},
    rustLifetime                              = {link='Normal'},
    rustEnum                                  = {link='Tag'},
    rustSelf                                  = {link='Statement'},
    rustEscape                                = {link='SpecialChar'},
    rustQuestionMark                          = {link='Keyword'},
    rustTrait                                 = {link='Function'},
    rustDeriveTrait                           = {link='Function'},
    rustStorage                               = {link='StorageClass'},

    -- csharp
    csClassType                         = {link='Normal'},
    csGenericBraces                     = {link='Normal'},
    csXmlTag                            = {link='Tag'},
    csModifier                          = {link='Keyword'},
    csAccessModifier                    = {link='Keyword'},
    csClass                             = {link='Keyword'},
    csNull                              = {link='Keyword'},
    csSpecialChar                       = {link='PreCondit'},
    csInterpolationDelimiter            = {link='PreCondit'},
    csType                              = {link='Type'},
    csStorage                           = {link='StorageClass'},

    -- UI
    WinSeparator                = {link='Normal'}, 
    StatusLine                  = {link='Normal'},
    LineNrAbove                 = {link='LineNr'}, 
    LineNrBelow                 = {link='LineNr'}, 
    CursorLineSign              = {link='SignColumn'}, 
    CursorLineFold              = {link='FoldColumn'}, 
    CursorIM                    = {link='Cursor'}, 
    lCursor                     = {link='Cursor'}, 
    TermCursor                  = {link='Cursor'}, 
    CurSearch                   = {link='Search'}, 
    Substitute                  = {link='Search'}, 
    IncSearch                   = {link='CurSearch'}, 
    StatusLineTerm              = {link='StatusLine'}, 
    StatusLineTermNC            = {link='StatusLineNC'}, 
    TabLine                     = {link='StatusLineNC'}, 
    TabLineFill                 = {link='TabLine'}, 
    FoldColumn                  = {link='SignColumn'}, 
    VertSplit                   = {link='WinSeparator'}, 
    EndOfBuffer                 = {link='NonText'}, 
    Whitespace                  = {link='NonText'}, 
    LspInlayHint                = {link='NonText'}, 
    LspCodeLens                 = {link='NonText'}, 
    VisualNOS                   = {link='Visual'}, 
    SnippetTabstop              = {link='Visual'}, 
    LspReferenceText            = {link='Visual'}, 
    LspSignatureActiveParameter = {link='Visual'}, 
    LspReferenceRead            = {link='LspReferenceText'}, 
    LspReferenceWrite           = {link='LspReferenceText'}, 
    LspCodeLensSeparator        = {link='LspCodeLens'}, 
    FloatBorder                 = {link='NormalFloat'}, 
    FloatTitle                  = {link='Title'}, 
    FloatFooter                 = {link='FloatTitle'}, 
    MsgArea                     = {link='NONE'}, 
    NormalNC                    = {link='NONE'}, 
    TermCursorNC                = {link='NONE'}, 
    PmenuKind                   = {link='Pmenu'}, 
    PmenuExtra                  = {link='Pmenu'}, 
    PmenuMatch                  = {link='Pmenu'}, 
    PmenuSbar                   = {link='Pmenu'}, 
    PmenuExtraSel               = {link='PmenuSel'}, 
    PmenuKindSel                = {link='PmenuSel'}, 
    PmenuMatchSel               = {link='PmenuSel'}, 
    WildMenu                    = {link='PmenuSel'}, 
    DiagnosticUnnecessary       = {link='Comment'}, 
    DiagnosticFloatingError     = {link='DiagnosticError'}, 
    DiagnosticVirtualTextError  = {link='DiagnosticError'}, 
    DiagnosticSignError         = {link='DiagnosticError'}, 
    DiagnosticFloatingWarn      = {link='DiagnosticWarn'}, 
    DiagnosticVirtualTextWarn   = {link='DiagnosticWarn'}, 
    DiagnosticSignWarn          = {link='DiagnosticWarn'}, 
    DiagnosticFloatingInfo      = {link='DiagnosticInfo'}, 
    DiagnosticVirtualTextInfo   = {link='DiagnosticInfo'}, 
    DiagnosticSignInfo          = {link='DiagnosticInfo'}, 
    DiagnosticFloatingHint      = {link='DiagnosticHint'}, 
    DiagnosticVirtualTextHint   = {link='DiagnosticHint'}, 
    DiagnosticSignHint          = {link='DiagnosticHint'}, 
    DiagnosticFloatingOk        = {link='DiagnosticOk'}, 
    DiagnosticVirtualTextOk     = {link='DiagnosticOk'}, 
    DiagnosticSignOk            = {link='DiagnosticOk'}, 
}
