local M = {}

M.links = {
    -- syntax
    ['@module']                     = {link='Normal'}, 
    ['@constructor']                = {link='Normal'}, 
    ['@variable']                   = {link='Normal'}, 
    ['@variable.builtin']           = {link='Normal'}, 
    ['@variable.parameter']         = {link='Normal'}, 
    ['@variable.parameter.builtin'] = {link='Normal'}, 
    ['@markup']                     = {link='Macro'}, 
    ['@markup.link']                = {link='Macro'}, 
    ['@markup.strong']              = {link='Macro'}, 
    ['@markup.italic']              = {link='Macro'}, 
    ['@markup.heading']             = {link='Macro'}, 
    ['@markup.underline']           = {link='Macro'}, 
    ['@markup.strikethrough']       = {link='Macro'}, 
    ['@type']                       = {link='Type'}, 
    ['@type.builtin']               = {link='Type'}, 
    ['@constant']                   = {link='Constant'}, 
    ['@constant.builtin']           = {link='Constant'}, 
    ['@string']                     = {link='String'}, 
    ['@string.regexp']              = {link='String'}, 
    ['@string.escape']              = {link='String'}, 
    ['@string.special']             = {link='String'}, 
    ['@string.special.url']         = {link='String'}, 
    ['@character']                  = {link='Character'}, 
    ['@character.special']          = {link='Character'}, 
    ['@function']                   = {link='Function'}, 
    ['@function.method']            = {link='Function'}, 
    ['@function.builtin']           = {link='Function'}, 
    ['@punctuation']                = {link='Delimiter'},
    ['@punctuation.special']        = {link='Delimiter'}, 
    ['@comment']                    = {link='Comment'}, 
    ['@comment.warning']            = {link='Comment'}, 
    ['@comment.error']              = {link='Comment'}, 
    ['@comment.note']               = {link='Comment'}, 
    ['@comment.todo']               = {link='Comment'}, 
    ['@tag']                        = {link='Tag'}, 
    ['@tag.builtin']                = {link='Tag'}, 
    ['@attribute']                  = {link='PreProc'}, 
    ['@attribute.builtin']          = {link='PreProc'}, 
    ['@module.builtin']             = {link='Special'}, 
    ['@keyword']                    = {link='Keyword'}, 
    ['@label']                      = {link='Label'}, 
    ['@boolean']                    = {link='Boolean'}, 
    ['@number']                     = {link='Number'}, 
    ['@number.float']               = {link='Float'}, 
    ['@property']                   = {link='Identifier'}, 
    ['@operator']                   = {link='Operator'}, 
    ['@diff.plus']                  = {link='Added'}, 
    ['@diff.minus']                 = {link='Removed'}, 
    ['@diff.delta']                 = {link='Changed'}, 
    -- clang
    cType         = {link='Type'},
    cTypeDef      = {link='Type'},
    cFormat       = {link='Special'},
    cStorageClass = {link='StorageClass'},
    -- rust
    rustSigil                          = {link='Normal'},
    rustFoldBraces                     = {link='Normal'},
    rustModPath                        = {link='Normal'},
    rustLifetime                       = {link='Normal'},
    ['@lsp.type.struct.rust']          = {link='Normal'},
    ['@lsp.type.enumMember.rust']      = {link='Special'},
    ['@lsp.type.enum.rust']            = {link='Special'},
    rustSelf                           = {link='Statement'},
    ['@lsp.type.selfKeyword.rust'] = {link='Statement'},
    ['@lsp.type.selfTypeKeyword.rust'] = {link='Keyword'},
    ['@lsp.typemod.selfKeyword.mutable.rust'] = {link='PreCondit'},
    ['@lsp.type.builtinType.rust']     = {link='Keyword'},
    rustDeriveTrait                    = {link='Function'},
    ['@lsp.type.interface.rust']       = {link='Function'},
    ['@lsp.typemod.interface.library.rust'] = {link='Function'},
    ['@lsp.type.parameter.rust']       = {link='Statement'},
    ['@lsp.typemod.parameter.mutable.rust'] = {link='PreCondit'},
    rustStorage                        = {link='StorageClass'},
    ['@lsp.type.const.rust']           = {link='Constant'},
    ['@lsp.type.variable.rust']        = {link='Constant'},
    ['@lsp.typemod.variable.mutable.rust'] = {link='Identifier'},
    -- csharp
    csClassType                         = {link='Normal'},
    csGenericBraces                     = {link='Normal'},
    csXmlTag                            = {link='Special'},
    ['@lsp.type.enumMember.cs']         = {link='Special'},
    ['@lsp.type.enum.cs']               = {link='Special'},
    csModifier                          = {link='Keyword'},
    csAccessModifier                    = {link='Keyword'},
    csClass                             = {link='Keyword'},
    csNull                              = {link='Keyword'},
    ['@lsp.typemod.class.static.cs']    = {link='Keyword'},
    ['@lsp.type.keyword.cs']            = {link='Keyword'},
    ['@lsp.type.builtinType.cs']        = {link='Keyword'},
    ['@lsp.type.interface.cs']          = {link='Function'},
    csSpecialChar                       = {link='PreCondit'},
    csInterpolationDelimiter            = {link='PreCondit'},
    ['@lsp.type.parameter.cs']          = {link='PreCondit'},
    csType                              = {link='Type'},
    csStorage                           = {link='StorageClass'},
    ['@lsp.type.method.cs']             = {link='Function'},
    ['@lsp.type.variable.cs']           = {link='Identifier'},
    ['@lsp.typemod.property.static.cs'] = {link='Constant'},
    ['@lsp.type.const.cs']              = {link='Constant'},

    -- UI
    WinSeparator                = {link='Normal'}, 
    StatusLine                  = {link='Normal'},
    LineNrAbove                 = {link='LineNr'}, 
    LineNrBelow                 = {link='LineNr'}, 
    CursorLineSign              = {link='SignColumn'}, 
    CursorLineFold              = {link='FoldColumn'}, 
    CursorIM                    = {link='Cursor'}, 
    lCursor                     = {link='Cursor'}, 
    TermCursor                  = {link='Cursor'}, 
    CurSearch                   = {link='Search'}, 
    Substitute                  = {link='Search'}, 
    IncSearch                   = {link='CurSearch'}, 
    StatusLineTerm              = {link='StatusLine'}, 
    StatusLineTermNC            = {link='StatusLineNC'}, 
    TabLine                     = {link='StatusLineNC'}, 
    TabLineFill                 = {link='TabLine'}, 
    FoldColumn                  = {link='SignColumn'}, 
    VertSplit                   = {link='WinSeparator'}, 
    EndOfBuffer                 = {link='NonText'}, 
    Whitespace                  = {link='NonText'}, 
    LspInlayHint                = {link='NonText'}, 
    LspCodeLens                 = {link='NonText'}, 
    VisualNOS                   = {link='Visual'}, 
    SnippetTabstop              = {link='Visual'}, 
    LspReferenceText            = {link='Visual'}, 
    LspSignatureActiveParameter = {link='Visual'}, 
    LspReferenceRead            = {link='LspReferenceText'}, 
    LspReferenceWrite           = {link='LspReferenceText'}, 
    LspCodeLensSeparator        = {link='LspCodeLens'}, 
    FloatBorder                 = {link='NormalFloat'}, 
    FloatTitle                  = {link='Title'}, 
    FloatFooter                 = {link='FloatTitle'}, 
    MsgArea                     = {link='NONE'}, 
    NormalNC                    = {link='NONE'}, 
    TermCursorNC                = {link='NONE'}, 
    PmenuKind                   = {link='Pmenu'}, 
    PmenuExtra                  = {link='Pmenu'}, 
    PmenuMatch                  = {link='Pmenu'}, 
    PmenuSbar                   = {link='Pmenu'}, 
    PmenuExtraSel               = {link='PmenuSel'}, 
    PmenuKindSel                = {link='PmenuSel'}, 
    PmenuMatchSel               = {link='PmenuSel'}, 
    WildMenu                    = {link='PmenuSel'}, 
    DiagnosticUnnecessary       = {link='Comment'}, 
    DiagnosticFloatingError     = {link='DiagnosticError'}, 
    DiagnosticVirtualTextError  = {link='DiagnosticError'}, 
    DiagnosticSignError         = {link='DiagnosticError'}, 
    DiagnosticFloatingWarn      = {link='DiagnosticWarn'}, 
    DiagnosticVirtualTextWarn   = {link='DiagnosticWarn'}, 
    DiagnosticSignWarn          = {link='DiagnosticWarn'}, 
    DiagnosticFloatingInfo      = {link='DiagnosticInfo'}, 
    DiagnosticVirtualTextInfo   = {link='DiagnosticInfo'}, 
    DiagnosticSignInfo          = {link='DiagnosticInfo'}, 
    DiagnosticFloatingHint      = {link='DiagnosticHint'}, 
    DiagnosticVirtualTextHint   = {link='DiagnosticHint'}, 
    DiagnosticSignHint          = {link='DiagnosticHint'}, 
    DiagnosticFloatingOk        = {link='DiagnosticOk'}, 
    DiagnosticVirtualTextOk     = {link='DiagnosticOk'}, 
    DiagnosticSignOk            = {link='DiagnosticOk'}, 
}

M.apply = function(spec)
    -- clear lsp highlights
    for _, group in ipairs(
        vim.fn.getcompletion("@lsp", "highlight")
    ) do
    		vim.api.nvim_set_hl(0, group, {})
    end
    -- apply p
    for k, v in pairs(spec) do
        vim.api.nvim_set_hl(0, k, v)
    end
    -- apply links
    for k, v in pairs(M.links) do
        vim.api.nvim_set_hl(0, k, v)
    end
end

return M
